apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-node-app-deployment
  labels:
    app: sample-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-node-app
  template:
    metadata:
      name: sample-node-app
      labels:
        app: sample-node-app
    spec:
      containers:
        - name: sample-node-app
          image: webinaracr.azurecr.io/sample-node-app:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: sample-node-app-svc
spec:
  selector:
    app: sample-node-app
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer